# Generated by Django 5.2.3 on 2026-04-20 11:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
