# Generated by Django 5.2.3 on 2026-04-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_visitorlog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='status_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
