# Generated by Django 5.2.3 on 2026-04-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_visitorlog_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The source/campaign name (used in ?source=)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ref_code', models.CharField(blank=True, help_text='Optional referral code to attach', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_visit_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
