# Generated by Django 5.2.3 on 2026-04-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_visitorlog_is_bot_visitorlog_visitor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='campaign',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='channel_group',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='content',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='medium',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='source_platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='term',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
