# Generated by Django 5.2.3 on 2026-04-23 00:00

from django.db import migrations, models


def backfill_campaign_utm_fields(apps, schema_editor):
    Campaign = apps.get_model('analytics', 'Campaign')

    for campaign in Campaign.objects.all():
        source = (campaign.name or '').strip().lower() or None
        if source:
            source = source[:100]

        campaign.source = campaign.source or source
        campaign.medium = campaign.medium or 'custom'
        campaign.landing_path = campaign.landing_path or '/'
        campaign.save(update_fields=['source', 'medium', 'landing_path'])


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_visitorlog_attribution_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign',
            field=models.CharField(blank=True, db_index=True, help_text='UTM campaign name', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='content',
            field=models.CharField(blank=True, help_text='Optional UTM content value', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='landing_path',
            field=models.CharField(blank=True, default='/', help_text='Relative landing path for the generated tracking URL', max_length=255),
        ),
        migrations.AddField(
            model_name='campaign',
            name='medium',
            field=models.CharField(blank=True, db_index=True, help_text='UTM medium, e.g. social, paid_social, email', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='source',
            field=models.CharField(blank=True, db_index=True, help_text='UTM source, e.g. instagram, google, newsletter', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='source_platform',
            field=models.CharField(blank=True, help_text='Optional UTM source platform value', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='term',
            field=models.CharField(blank=True, help_text='Optional UTM term value', max_length=150, null=True),
        ),
        migrations.RunPython(backfill_campaign_utm_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(help_text='Admin-facing label for this tracking campaign', max_length=100, unique=True),
        ),
    ]
