# Generated by Django 5.2.3 on 2026-04-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_campaign_utm_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='fbclid',
            field=models.CharField(blank=True, help_text='Optional Facebook Click ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='gclid',
            field=models.CharField(blank=True, help_text='Optional Google Click ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='fbclid',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='gclid',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
