# Generated by Django 5.2.3 on 2026-04-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_campaign_fbclid_campaign_gclid_visitorlog_fbclid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='fbclid',
            field=models.CharField(blank=True, help_text='Optional Facebook Click ID', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='gclid',
            field=models.CharField(blank=True, help_text='Optional Google Click ID', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='landing_path',
            field=models.CharField(blank=True, default='/', help_text='Relative landing path for the generated tracking URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='fbclid',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='gclid',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='path',
            field=models.CharField(max_length=500),
        ),
    ]
