# Generated by Django 5.2.3 on 2025-06-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='tracking_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
