# Generated by Django 5.2.3 on 2025-06-18 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_template_tracking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='tracking_id',
        ),
    ]
