# Generated by Django 5.2.3 on 2025-06-18 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_purchasedtemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='svg_content',
        ),
    ]
