# Generated by Django 5.2.3 on 2025-06-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_template_svg_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='svg',
            field=models.TextField(default=''),
        ),
    ]
