# Generated by Django 5.2.3 on 2025-06-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_template_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedtemplate',
            name='form_fields',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='template',
            name='form_fields',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='purchasedtemplate',
            name='test',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='template',
            name='svg',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='template',
            name='type',
            field=models.CharField(choices=[('tool', 'Tool'), ('design', 'Design')], max_length=20),
        ),
    ]
