# Generated by Django 5.2.3 on 2025-06-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_purchasedtemplate_form_fields_template_form_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedtemplate',
            name='form_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='template',
            name='form_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
