# Generated by Django 5.2.3 on 2025-06-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_purchasedtemplate_form_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedtemplate',
            name='status',
            field=models.CharField(choices=[('', ''), ('processing', 'Processing'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('error_message', 'Error Message')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchasedtemplate',
            name='test',
            field=models.BooleanField(default=True),
        ),
    ]
