# Generated by Django 5.2.3 on 2025-06-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_purchasedtemplate_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedtemplate',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
