# Generated by Django 5.2.3 on 2025-06-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_purchasedtemplate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedtemplate',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
