# Generated by Django 5.2.3 on 2025-06-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_purchasedtemplate_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedtemplate',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchasedtemplate',
            name='status',
            field=models.CharField(choices=[('', ''), ('processing', 'Processing'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('error_message', 'Error Message')], default='processing', max_length=20),
        ),
    ]
