# Generated by Django 5.2.3 on 2025-07-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_purchasedtemplate_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='hot',
            field=models.BooleanField(default=False),
        ),
    ]
