# Generated by Django 5.2.3 on 2025-08-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_template_hot'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='banner',
            field=models.ImageField(blank=True, help_text='Banner image for the template', null=True, upload_to='template_banners/'),
        ),
    ]
