# Generated by Django 5.2.3 on 2025-08-31 01:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_template_banner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchasedtemplate',
            index=models.Index(fields=['buyer'], name='api_purchas_buyer_i_42df18_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasedtemplate',
            index=models.Index(fields=['template'], name='api_purchas_templat_77de59_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasedtemplate',
            index=models.Index(fields=['status'], name='api_purchas_status_829e5f_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasedtemplate',
            index=models.Index(fields=['tracking_id'], name='api_purchas_trackin_91ff64_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasedtemplate',
            index=models.Index(fields=['created_at'], name='api_purchas_created_59fb6c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasedtemplate',
            index=models.Index(fields=['buyer', 'status'], name='api_purchas_buyer_i_d4562a_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['type'], name='api_templat_type_d4ff45_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['hot'], name='api_templat_hot_25285e_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['created_at'], name='api_templat_created_b81313_idx'),
        ),
    ]
