# Generated by Django 5.2.3 on 2025-09-01 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_purchasedtemplate_api_purchas_buyer_i_42df18_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedtemplate',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='api.template'),
        ),
    ]
