# Generated by Django 5.2.3 on 2025-09-01 12:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_purchasedtemplate_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tools',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='template',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='api.tool'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['tool'], name='api_templat_tool_id_a5db6d_idx'),
        ),
    ]
