# Generated by Django 5.2.3 on 2025-10-06 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_tool_template_tool_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='purchasedtemplate',
            name='api_purchas_status_829e5f_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchasedtemplate',
            name='api_purchas_buyer_i_d4562a_idx',
        ),
        migrations.RemoveField(
            model_name='purchasedtemplate',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='purchasedtemplate',
            name='status',
        ),
    ]
