# Generated by Django 5.2.3 on 2025-10-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this template is visible to users'),
        ),
        migrations.AddField(
            model_name='tool',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this tool is visible to users'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['is_active'], name='api_templat_is_acti_978198_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['is_active'], name='api_tool_is_acti_71b031_idx'),
        ),
    ]
