# Generated by Django 5.2.3 on 2025-10-27 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_template_is_active_tool_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='template',
            name='api_templat_is_acti_978198_idx',
        ),
        migrations.RemoveIndex(
            model_name='tool',
            name='api_tool_is_acti_71b031_idx',
        ),
        migrations.RemoveField(
            model_name='template',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='is_active',
        ),
    ]
