# Generated by Django 5.2.3 on 2025-11-18 11:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_template_keywords_purchasedtemplate_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Font family name (e.g., 'OCR B', 'Arial')", max_length=255)),
                ('font_file', models.FileField(help_text='Font file (TTF, OTF, WOFF, WOFF2)', upload_to='fonts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='api_font_name_3b3d65_idx')],
            },
        ),
        migrations.AddField(
            model_name='template',
            name='fonts',
            field=models.ManyToManyField(blank=True, help_text='Font files used in this template', related_name='templates', to='api.font'),
        ),
    ]
