# Generated by Django 5.2.3 on 2025-12-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_font_template_fonts'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedtemplate',
            name='svg_file',
            field=models.FileField(blank=True, help_text='SVG file storage', null=True, upload_to='purchased_templates/svgs/'),
        ),
        migrations.AddField(
            model_name='template',
            name='svg_file',
            field=models.FileField(blank=True, help_text='SVG file storage', null=True, upload_to='templates/svgs/'),
        ),
    ]
