# Generated by Django 5.2.3 on 2025-12-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_purchasedtemplate_svg_file_template_svg_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_address', models.CharField(blank=True, help_text='Crypto address for payments', max_length=255)),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp number for manual payments', max_length=50)),
                ('manual_purchase_text', models.TextField(blank=True, help_text='Instructions for manual purchases')),
                ('dev_name_obfuscated', models.TextField(blank=True, help_text='Answer to: Second name of developer')),
                ('owner_name_obfuscated', models.TextField(blank=True, help_text='Answer to: Second name of owner')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
