# Generated by Django 5.2.3 on 2025-12-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransformVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rotate', models.FloatField(default=0.0)),
                ('scale', models.FloatField(default=1.0)),
                ('translateX', models.FloatField(default=0.0)),
                ('translateY', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transform Variable',
                'verbose_name_plural': 'Transform Variables',
                'ordering': ['name'],
            },
        ),
    ]
