# Generated by Django 5.2.3 on 2025-12-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_transformvariable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transformvariable',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Transform Variable', 'verbose_name_plural': 'Transform Variables'},
        ),
        migrations.RenameField(
            model_name='transformvariable',
            old_name='rotate',
            new_name='value',
        ),
        migrations.AddField(
            model_name='transformvariable',
            name='category',
            field=models.CharField(choices=[('rotate', 'Rotation'), ('scale', 'Scale'), ('translateX', 'Position X'), ('translateY', 'Position Y')], default='rotate', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='transformvariable',
            unique_together={('name', 'category')},
        ),
        migrations.AlterField(
            model_name='transformvariable',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='transformvariable',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='transformvariable',
            name='translateX',
        ),
        migrations.RemoveField(
            model_name='transformvariable',
            name='translateY',
        ),
    ]
