# Generated by Django 5.2.3 on 2026-01-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_transformvariable_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['is_active'], name='api_templat_is_acti_978198_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['is_active'], name='api_tool_is_acti_71b031_idx'),
        ),
    ]
