# Generated by Django 5.2.3 on 2026-01-15 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_template_is_active_tool_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='font',
            name='family',
            field=models.CharField(blank=True, help_text="CSS Font Family (e.g., 'Roboto'). Groups variants.", max_length=255),
        ),
        migrations.AddField(
            model_name='font',
            name='style',
            field=models.CharField(default='normal', help_text="CSS Font Style (e.g., 'normal', 'italic')", max_length=50),
        ),
        migrations.AddField(
            model_name='font',
            name='weight',
            field=models.CharField(default='normal', help_text="CSS Font Weight (e.g., 'normal', 'bold', '400', '700')", max_length=50),
        ),
        migrations.AddField(
            model_name='purchasedtemplate',
            name='fonts',
            field=models.ManyToManyField(blank=True, help_text='Fonts copied from template at purchase time', related_name='purchased_templates', to='api.font'),
        ),
    ]
