# Generated by Django 5.2.3 on 2026-03-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_sitesettings_tiktok_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='template_cache_version',
            field=models.BigIntegerField(default=0, help_text='Global version for template cache busting'),
        ),
    ]
