# Generated by Django 5.2.3 on 2026-04-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_sitesettings_template_cache_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='show_community_on_hover',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_instagram_on_hover',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_telegram_on_hover',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_tiktok_on_hover',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_twitter_on_hover',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_whatsapp_on_hover',
            field=models.BooleanField(default=True),
        ),
    ]
