# Generated by Django 5.2.3 on 2026-04-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_aichatsession_aichatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_ai_features',
            field=models.BooleanField(default=True, help_text='Global kill-switch for AI Chat and assistant features'),
        ),
    ]
