# Generated by Django 5.2.3 on 2026-04-21 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_sitesettings_enable_ai_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_referrals',
            field=models.BooleanField(default=True, help_text='Enable the referral program'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='min_referral_deposit',
            field=models.DecimalField(decimal_places=2, default=6.0, help_text='Minimum deposit required by the referred user to trigger reward', max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='referral_reward_amount',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Amount given to the referrer', max_digits=10),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_rewarded', models.BooleanField(default=False)),
                ('reward_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_referral', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
