# Generated by Django 5.2.3 on 2026-04-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_sitesettings_enable_referrals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='referral_percentage',
            field=models.DecimalField(decimal_places=2, default=33.33, help_text='Percentage of the min deposit given to referrer (e.g. 33.33)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='referral_reward_amount',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='[Legacy] Static reward amount', max_digits=10),
        ),
    ]
