# Generated by Django 5.2.3 on 2026-04-21 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_sitesettings_referral_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='min_withdrawal_threshold',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Minimum withdrawal amount for referral balance', max_digits=10),
        ),
        migrations.AlterField(
            model_name='referral',
            name='is_rewarded',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referred_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_referral', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='referral_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Percentage of every deposit given to both referrer and invitee (e.g. 10.00)', max_digits=5),
        ),
    ]
