# Generated by Django 5.2.3 on 2026-04-21 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_sitesettings_min_withdrawal_threshold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='referral_reward_amount',
        ),
    ]
