# Generated by Django 5.2.3 on 2026-06-12 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_remove_sitesettings_referral_reward_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={'ordering': ['-is_featured', '-created_at']},
        ),
        migrations.AddField(
            model_name='tutorial',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tool',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorial', to='api.tool'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='template',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorial', to='api.template'),
        ),
        migrations.AddConstraint(
            model_name='tutorial',
            constraint=models.CheckConstraint(condition=models.Q(('template__isnull', False), ('tool__isnull', False), _negated=True), name='tutorial_single_scope'),
        ),
    ]
