# Generated by Django 5.2.3 on 2026-04-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='source',
            field=models.CharField(blank=True, help_text='Traffic source (e.g. Facebook, Twitter, referral)', max_length=100, null=True),
        ),
    ]
