# Generated by Django 5.2.3 on 2026-04-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_set_default_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='source',
            field=models.CharField(blank=True, default='Organic', help_text='Traffic source (e.g. Facebook, Twitter, referral)', max_length=100, null=True),
        ),
    ]
