# Generated by Django 5.2.3 on 2026-04-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='source',
            field=models.CharField(blank=True, default='Direct', help_text='Traffic source (e.g. google, facebook, direct)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='medium',
            field=models.CharField(blank=True, default='(none)', help_text='Acquisition medium (e.g. organic, referral, cpc)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='campaign',
            field=models.CharField(blank=True, help_text='Acquisition campaign name', max_length=150, null=True),
        ),
    ]
