# Generated by Django 5.2.3 on 2026-04-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_medium_user_campaign_and_source_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='content',
            field=models.CharField(blank=True, help_text='Acquisition content', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fbclid',
            field=models.CharField(blank=True, help_text='Facebook Click ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gclid',
            field=models.CharField(blank=True, help_text='Google Click ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='source_platform',
            field=models.CharField(blank=True, help_text='Acquisition source platform', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='term',
            field=models.CharField(blank=True, help_text='Acquisition term', max_length=150, null=True),
        ),
    ]
