# Generated by Django 5.2.3 on 2026-04-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_content_user_fbclid_user_gclid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fbclid',
            field=models.CharField(blank=True, help_text='Facebook Click ID', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gclid',
            field=models.CharField(blank=True, help_text='Google Click ID', max_length=500, null=True),
        ),
    ]
