# Generated by Django 5.2.3 on 2025-07-01 11:06

import wallet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tx_id',
            field=models.CharField(default=wallet.models.generate_tx_id, max_length=36, unique=True),
        ),
    ]
